### PR TITLE
Merge my WP Docker script with 10up's image

### PR DESCRIPTION
**Pull request by jamesgol**
This allows multiple dev environments to co-exist on the same host.

For a while I've been using a script similar to this to setup a simple dev environment.
Only tested on Linux but should work on OSX

Wanted to have something similar to how VVV works but without using a VM

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Wow, love this PR, only thing I'm wondering about is why it should be run as root. Beyond that, this does a great job at improving the usability of this from a new user standpoint (and for people who don't want to get into the mucky muck of file hacks).

**Comment by cr101** [comment]
@jamesgol Does it work on Windows as well?

**Comment by jamesgol** [comment]
No there is no Windows batch script included.  Someone would have to put one together, I haven't used Windows regularly in forever, does Windows have something like /etc/hosts that it uses for lookups?

**Comment by roelveldhuizen** [comment]
@jamesgol Windows has the same file. Generally found in: ```C:\Windows\System32\drivers\etc```

**Pull request closed without merging**
