### PR TITLE
Feature/linux folder permissions

### PR DESCRIPTION
**Pull request by moraleida**
## **This is done, but needs user testing.**

This addresses #17 by creating a separate script that will setup the needed variables in `docker-compose.override.yml` before building the php-fpm image.

Things we need to accomplish:

- [x] Create a script to get user's name and UID
- [x] Automate adding this information to `docker-compose.override.yml` so it's available during build
- [x] Check for args during build and create mapped users in the `php-fpm` container if needed
- [x] Add instructions to `readme.md` to make sure users on Linux hosts run `bin/linux-info.sh` before the first `docker-compose up`
- [x] Check if users are mapped and run the other scripts as the mapped user instead of `www-data` when possible

### CODE REVIEW

**Comment by moraleida** [comment]
uh-oh, I guess #48 killed this, thoughts @cmmarslender ?

**Comment by moraleida** [comment]
@tlovett1 @cmmarslender I think this is ready for review again. I've fundamentally changed the original approach to work with images instead of Dockerfiles and to be safe and unobtrusive for Windows and Mac users. I've been using this approach for about a year now without issue on Linux.

**How it works:**

There are 3 new scripts:
- **hosts-setup.sh**: checks if `docker-compose.overrides.yml` exists and creates it with the user's username and UID as environment variables. The overrides file also maps a new `container.setup.sh` script into the `phpfpm` container and adds a command to run it at the end of the build.

- **container-setup.sh**: this is run only when building the container. The script checks if there are environment variables defining an username and UID and creates that user inside the `phpfpm` container. It makes sure that the user belongs to the `www-data` group, owns `/var/www/html` and that new files under that folder will inherit owners and groups.

- **helper.sh**: this creates a helper function to determine if we should use the default `www-data` user or the user defined on the overrides file. If there aren't variables set in an overrides file, it falls back to `www-data`.

Along with that, there are calls to the helper function on the top of `setup.sh` and `wp.sh` , to determine which user should run the docker-compose calls.

**What changes in the install process?**

- Windows and Mac users won't see any changes.
- Linux users have an extra step during build. They run `bin/host-setup.sh` before the first `docker-compose up`.

Fixes #17

**Comment by ironland** [comment]
@moraleida I was tinkering with this project on my Win 10 + WSL setup and was about to write to this thread about any possible progress. Nice to see that you've done work on this! 

I cloned your repo and the branch and tried to run the host-setup.sh -script, but it fails and the output is the following:

```
sh bin/host-setup.sh
bin/host-setup.sh: 3: bin/host-setup.sh: Bad substitution
0+1 records in
0+1 records out
223 bytes copied, 0.004689 s, 47.6 kB/s
The docker-compose.override.yml file was created
```
So it fails and doesn't generate the docker-compose.override.yml -file. At least on my WSL-setup. Don't know if this is the proper place to message, but I thought that it would be nice to inform you 👍 

**edit:** Actually, at least on my setup, the `parent_path` is the root path of the project so we never go to the bin folder. That way the override-file was generated but outside the root of the project. Also the double quotes on the volume mounts don't play nice. Should they be escaped when echoed in to the file?

**Comment by moraleida** [comment]
@ironland thanks for testing. 

There are a few different ways people run wp-local-docker on Windows and I'm not sure which one we're recommending. If I understand correctly, then, running from within WSL you also run into #17 using the current master?

**edit:** I'm able to reproduce your issue on WSL. It seems like Windows is returning different paths depending on which shell you call the script from and how you call it.

- On Git Bash I get "/c/Users/.../bin" which is correct, no matter how I call

- On WSL the path always starts with "/mnt/c/Users/..." which it can't find because it's not expecting the /mnt/ part. On top of that, `bin/hosts-setup.sh` and `./bin/hosts-setup.sh` correctly find the bin folder, `sh bin/hosts-setup.sh` doesn't.

**Comment by ironland** [comment]
@moraleida allright! Thanks for a quick reply. 🙏 

I ran it with `sh` and did not try to run it with `./`. I just made the override file manually 👍 .

`On WSL the path always starts with "/mnt/c/Users/..." which it can't find because it's not expecting the /mnt/ part. ` 
- Yeah, that's the way WSL mounts the volumes from Windows by default. On the latest release though, they have made it possible to adjust the root path of the mounts via wsl.conf. So my paths are starting from `/c/` instead of `/mnt/c/`. 👍 The problem for me was only the bin path vs the project root path.

- I actually had a few problems. First was #96 and as I have not been able to fix it myself during these past days, I've just commented out the mounting of the log path. Then, when trying to run the `setup.sh`, permission errors caused quite many issues. For instance, WP CLI wasn't able to connect to MySQL so the setup wasn't able to install WP and so on. I'll try again now, when the UID is different 👍  

**edit:** I tried to run the setup script and the errors were similar to before when I had not had the override-file. Here's the output:
```
Warning: Failed to create directory '/home/xyz/.wp-cli/cache/': mkdir(): Permission denied.
md5 hash verified: f168643b20001cc46b3478facd4f539b
Success: WordPress downloaded.
ERROR 1130 (HY000): Host '172.20.0.6' is not allowed to connect to this MySQL server
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
Error: 'wp-config.php' not found.
Either create one manually or use `wp config create`.
Do you want to remove the default content? [y/n] n
Installation done.
------------------
Admin username: xxx
Admin password: xxx
Couldn't get a file descriptor referring to the console
```
So there's the #107 error and then a couple of issues that I'm guessing are related to permission errors as well 🤔 not sure though.

**Comment by ironland** [comment]
I can also open a new issue if that is more clear, instead of commenting here 👌

**Comment by moraleida** [comment]
> I can also open a new issue if that is more clear, instead of commenting here ok_hand

This is fine, I guess WSL counts as Linux after all. Also we might need to change approaches once again because WP Snapshots is running as root on Linux and causing all sorts of issues too. I'll get back to this at some point.

**Comment by ironland** [comment]
@moraleida all right!

**Comment by moraleida** [comment]
wp-local-docker has changed a lot in the year since I started working on this PR, so here's a list of things we still need to fix before merging:

- [ ] wpsnapshots runs as root, needs to be able to run as $USER
- [ ] add detailed instructions for WSL and make sure the base linux changes account for it
- [ ] move from setting environmental variables in `docker.compose.overrides.yml` to a proper `.env` file that can be reused across containers

**Comment by cmmarslender** [comment]
Linux permission issues should be resolved with changes to the php and wpsnapshots images merged in https://github.com/10up/wp-local-docker-images/commit/d51e31d44f0cba0e525bad01b639a2b2c1faf27d

**Pull request closed without merging**
